development: &default
  database: pitonneux_development
  adapter: postgresql
  encoding: utf8
  pool: 5

test: &test
  <<: *default
  database: pitonneux_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: pitonneux_production
